### ISSUE TITLE
fatal error: mavlink.h: No such file or directory

### ISSUE THREAD

**Issue by Kumaron** [AlexisTM/aero-optical-flow-ros#1]
Hi AlexisTM,
    I cloned your repository and tried to build it, but errors occurred.
    "fatal error: mavlink.h: No such file or directory".
    I didn't find mavlink.h in aero-optical-ros/src/, could you tell me how to solve this?
    
    Thanks in advance.

**Comment by AlexisTM** [comment]
Did you recursively clone the repo?
If not, update the submodules :)

**Comment by AlexisTM** [comment]
git clone --recursive http://github.com/AlexisTM/aero-optical-flow-ros
    # or clone and then use git submodule update --init --recursive

**Comment by AlexisTM** [comment]
Closed due to inactivity after a solution.

**Comment by koyahatataku** [comment]
I also confronted with the same issue and solved it with installing header files below. You might edit header file path in the source codes  :
https://github.com/mavlink/c_library_v1/tree/master/common

**Comment by AlexisTM** [comment]
You should use MAVLink V2
